version: '3.0.{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TARGET: MSVC
      VisualStudioVersion: 14.0
      CMAKE_GENERATOR_ARGS: -G "Visual Studio 14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TARGET: MSVC
      VisualStudioVersion: 15.0
      CMAKE_GENERATOR_ARGS: -G "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TARGET: MSVC
      VisualStudioVersion: 15.0
      CMAKE_GENERATOR_ARGS: -G "Visual Studio 15 2017" -A x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TARGET: MSVC
      VisualStudioVersion: 16.0
      CMAKE_GENERATOR_ARGS: -G "Visual Studio 16 2019" -A x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TARGET: MinGW
      CMAKE_GENERATOR_ARGS: -G "MinGW Makefiles"
      MINGW_PREFIX: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TARGET: MinGW
      CMAKE_GENERATOR_ARGS: -G "MinGW Makefiles"
      MINGW_PREFIX: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64

install:
  # CMake's MinGW generator doesn't play nice with git's sh.exe
  - ps: Get-Command sh.exe -All | Remove-Item

build_script:
  - mkdir build
  - cd build
  - if [%TARGET%]==[MinGW] (
      set "PATH=%MINGW_PREFIX%\bin;%PATH%" )
  - cmake %CMAKE_GENERATOR_ARGS% -DCMAKE_BUILD_TYPE=Debug -DST_BUILD_TESTS=ON ..
  - if [%TARGET%]==[MSVC] (
      cmake --build . --config Debug &&
      cmake --build . --config Debug --target test )
  - if [%TARGET%]==[MinGW] (
      mingw32-make &&
      mingw32-make test )
